on: 
  push:
    branches: make-conflict

jobs:
  createConflict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get file and commit change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          curl -o cube.ipynb https://raw.githubusercontent.com/ttimbers/r-cube-commit-source/main/cube.ipynb
          git commit -m "Here's a fix to the file!" -a
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
